remove png from metadata attributes and beautify JSON output
victorquanlam/cryptopunk-nft-generator pull request #6
Opened 2022-01-25 04:29 UTC by victoryeo

2022-01-25 04:40 UTC, victorquanlam requested changes

2022-01-25 04:40 UTC, victorquanlam commented on index.js
> +  //console.log(traitTypes)
please remove console.log

2022-01-25 04:40 UTC, victorquanlam commented on index.js
> +  //console.log(combinations)
please remove console.log

2022-01-25 04:40 UTC, victorquanlam commented on index.js
> +  //deep copy
great!!

2022-01-26 05:22 UTC, victoryeo commented on index.js
> +  //console.log(traitTypes)
console.log is removed.

2022-01-26 05:22 UTC, victoryeo commented on index.js
> +  //console.log(combinations)
console.log is removed.

2022-01-26 07:25 UTC, victorquanlam commented on index.js
> +  //console.log(traitTypes)
Thanks

2022-01-26 07:26 UTC, merged